[Deploy] Setup Travis
renown-fruit/dai-payroll pull request #14
Opened 2019-02-19 00:25 UTC by adibas03

2019-02-19 11:59 UTC, coderwithattitude approved these changes

2019-02-19 12:00 UTC, coderwithattitude requested changes
please add gh-pages branch

2019-03-07 19:15 UTC, adibas03 commented
@coderwithattitude  All set

2019-03-09 17:15 UTC, coderwithattitude approved these changes

2019-03-09 17:16 UTC, merged